### ISSUE TITLE
ArgumentNullException Exception during install of SignalR Scaleout schema tables

### ISSUE THREAD

**Issue by mvcutter** [aspnet/SignalR-SqlServer#15]
Running versions
Microsoft.AspNet.SignalR.Server 3.0.0-beta8
Microsoft.AspNet.SignalR.SqlServer 3.0.0-beta8

Exception below

```
Exception:  Error trying to install SQL server objects, trying again in 2 seconds: {0}
System.ArgumentNullException: Value cannot be null.
Parameter name: stream
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream)
   at Microsoft.AspNet.SignalR.AssemblyExtensions.StringResource(Assembly assembly, String name)
   at Microsoft.AspNet.SignalR.SqlServer.SqlInstaller.Install()
   at Microsoft.AspNet.SignalR.SqlServer.SqlMessageBus.Initialize(Object state)
```

It appears that the AssemblyExtensions.StringResource method is expecting the variable 'resourceStream' to not be null, it also appears there is no way to bypass this step to create the tables yourself manually.

Exception occurs in "SqlInstaller.Install()" method call.
var script = GetType().GetTypeInfo().Assembly.StringResource("install.sql");

**Comment by rmja** [comment]
I am having the same problem, and it remains in rc1. I fixed it using the following steps:

Replace https://github.com/aspnet/SignalR-SqlServer/blob/dev/src/Microsoft.AspNet.SignalR.SqlServer/project.json#L11 with:

```
"namedResource": {
    "Microsoft.AspNet.SignalR.SqlServer.install.sql": "install.sql",
    "Microsoft.AspNet.SignalR.SqlServer.send.sql": "send.sql"
  },
```

Replace https://github.com/aspnet/SignalR-SqlServer/blob/dev/src/Microsoft.AspNet.SignalR.SqlServer/SqlInstaller.cs#L38 with:

```
var script = GetType().GetTypeInfo().Assembly.StringResource("Microsoft.AspNet.SignalR.SqlServer.install.sql");
```

Replace https://github.com/aspnet/SignalR-SqlServer/blob/dev/src/Microsoft.AspNet.SignalR.SqlServer/SqlSender.cs#L32 with:

```
var insertDml = GetType().GetTypeInfo().Assembly.StringResource("Microsoft.AspNet.SignalR.SqlServer.send.sql");
```

That should work

**Comment by ZeBobo5** [comment]
Same error on 0.1.0 ... The sql scripts seem to be not embbeded

**Comment by dimangulov** [comment]
I have the same error in 0.2.0
